---
kind: "pipeline"
name: "default"

steps:
        - name: "unit tests"
          image: "registry.kalehmann.de/testing/pysfedit:latest"
          commands:
                - "xvfb-run -a python3 -m unittest -v"

image_pull_secrets:
        - "dockerconfigjson"
...