---
language: 'minimal'
addons:
    apt:
        packages:
            - 'gir1.2-gtk-3.0'
            - 'python3'
            - 'python3-gi-cairo'
            - 'python3-pillow'
            - 'python3-pkg-resources'
            - 'xvfb'
            - 'xauth'
        update: true
dist: 'bionic'
script:
    - 'xvfb-run -a python3 -m unittest -v'
...